apiVersion: v1
kind: Service
metadata:
  name: cloud-resume-service
spec:
  type: NodePort
  selector:
    app: cloud-resume
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080  # You can specify a port or let Kubernetes assign one
