apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: staging-

replicas:
- name: cloud_resume-deployment
  count: 3  # Staging mirrors production replica count