apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: prod-

replicas:
- name: cloud_resume-deployment
  count: 3  # Production uses more replicas for high availability